# Generated by Django 5.1.4 on 2025-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                ("date", models.CharField(blank=True, max_length=50, null=True)),
                ("points", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "managed": True,
            },
        ),
    ]
