# Generated by Django 5.1.4 on 2025-05-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
