# Generated by Django 5.2.1 on 2025-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_remove_order_order_id_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="type",
            field=models.CharField(default="personal", max_length=32),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
